# Generated by Django 4.1.5 on 2023-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cfirst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Dfirst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
