# Generated by Django 4.1.5 on 2023-03-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_c_first_user_d_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='C_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='D_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='C_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='D_first',
            field=models.IntegerField(default=0),
        ),
    ]
