# Generated by Django 4.1.5 on 2023-03-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_c_second_user_d_second_alter_user_c_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='C_first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='D_first',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
