# Generated by Django 4.1.5 on 2023-03-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_c_first_remove_user_d_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='C_second',
        ),
        migrations.RemoveField(
            model_name='user',
            name='D_second',
        ),
    ]
