# Generated by Django 4.1.5 on 2023-03-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
