# Generated by Django 4.1.5 on 2023-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_picture_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_photo/%Y/%m/%d'),
        ),
    ]
