# Generated by Django 4.1.5 on 2023-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_picture_user_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='file',
        ),
    ]
