# Generated by Django 4.1.5 on 2023-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_profile_photo_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d'),
        ),
    ]
