# Generated by Django 4.1.5 on 2023-05-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d', verbose_name='profile_photo'),
        ),
    ]
