# Generated by Django 4.1.5 on 2023-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
