# Generated by Django 4.1.5 on 2023-05-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_name_user_firstname_user_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
