# Generated by Django 4.1.5 on 2023-05-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_firstname_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
