# Generated by Django 4.1.5 on 2023-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_user_day_remove_user_file_remove_user_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d', verbose_name='profile_photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
