# Generated by Django 4.1.5 on 2023-06-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_requests',
        ),
    ]
