# Generated by Django 4.1.5 on 2023-06-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
