# Generated by Django 4.1.5 on 2023-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
