# Generated by Django 4.1.5 on 2023-09-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_post_share_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='post',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
