### Variables ###

@baseUrl = http://127.0.0.1:8000
#@baseUrl = http://154.41.254.253:8000/
#@baseUrl = https://ashberri-api.onrender.com/

### Home
GET {{baseUrl}}

### Loging
POST  {{baseUrl}}/account/login/
Content-Type: application/json

{
  "email": "ashish@gmail.com",
  "password": "admin"
}

###List of all user

GET {{baseUrl}}/account/getallusers/

### User Profile (loged in)
GET {{baseUrl}}/account/profile/