# Generated by Django 4.1.5 on 2023-06-11 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0003_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FriendShip',
        ),
    ]
